name: ci

on:
  push:
    branches: [main, feat/microfrontend]
  pull_request:
    branches: [main, feat/microfrontend]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['test', 'lint']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run tests and lint
        uses: borales/actions-yarn@v4
        with: 
          cmd: ${{ matrix.command }}